# Generated by Django 3.1.3 on 2020-11-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('año', models.IntegerField(verbose_name='año')),
                ('precio', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('Científico', 'Científico'), ('Literatura', 'Literatura'), ('Biografía', 'Biografía'), ('Cómic', 'Cómic')], max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
